services:
  web:
    build: .
    container_name: flask_app
    ports:
      - 5000:5000
    environment:
      - DB_HOST=db
      - DB_NAME=appdb
      - DB_USER=appuser
      - DB_PASS=apppass
    depends_on:
      - db    
  db:
    image: postgres:14
    container_name: pgdb
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata:
